"""Add user to interactions

Revision ID: 0cf0b3a342d6
Revises: 29d2f3c7e7ba
Create Date: 2025-05-22 10:53:09.837495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf0b3a342d6'
down_revision = '29d2f3c7e7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
