"""Add KnowledgeBase model and Assistant-KnowledgeBase association

Revision ID: 10855fbf803d
Revises: e8f9c2d4a5b7
Create Date: 2025-07-31 19:31:39.767620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10855fbf803d'
down_revision = 'e8f9c2d4a5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgebase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assistant_knowledgebase',
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('knowledgebase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.id'], ),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebase.id'], ),
    sa.PrimaryKeyConstraint('assistant_id', 'knowledgebase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_knowledgebase')
    op.drop_table('knowledgebase')
    # ### end Alembic commands ###
