"""add assistant to conversation

Revision ID: 794cbe51a371
Revises: b9791218a532, c88ac0c951d2
Create Date: 2025-07-07 13:45:03.127827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794cbe51a371'
down_revision = ('b9791218a532', 'c88ac0c951d2')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('assistant_name')

    # ### end Alembic commands ###
