"""Rename 'assistant_name' to 'name'

Revision ID: 85b55a4372b7
Revises: c5d153057a94
Create Date: 2025-03-19 16:37:23.182815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85b55a4372b7'
down_revision = 'c5d153057a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent')
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('assistant_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    op.create_table('agent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filenames', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agent_pkey')
    )
    # ### end Alembic commands ###
