"""Remove filenames column from Assistant

Revision ID: 896de87742d0
Revises: 10855fbf803d
Create Date: 2025-08-01 12:01:16.863731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '896de87742d0'
down_revision = '10855fbf803d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.drop_column('filenames')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filenames', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
