"""Remove filenames column from knowledgebase table

Revision ID: a1b2c3d4e5f6
Revises: 10855fbf803d
Create Date: 2025-08-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '10855fbf803d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'filenames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('filenames', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###