"""empty message

Revision ID: dbac2434ce78
Revises: 0cf0b3a342d6
Create Date: 2025-06-04 11:39:02.840072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbac2434ce78'
down_revision = '0cf0b3a342d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=True))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
