apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tangerine-proxy-cookie-secret

parameters:
- name: SECRET
  required: true

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: tangerine-proxy-cookie-secret
  type: Opaque
  data:
    clientSecret: ${SECRET}
