---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tangerine-backend

parameters:
  - name: LLM_BASE_URL
    value: http://vllm.llm-hosting.svc.cluster.local:8000/v1
  - name: EMBED_BASE_URL
    value: http://text-embeddings-inference:3000/v1
  - name: LLM_MODEL_NAME
    value: mistralai/Mistral-7B-Instruct-v0.2
  - name: EMBED_MODEL_NAME
    value: Snowflake/snowflake-arctic-embed-m-long
  - name: EMBED_QUERY_PREFIX
    value: "Represent this sentence for searching relevant passages"
  - name: LLM_TEMPERATURE
    value: "0.3"
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 512Mi
  - name: CPU_REQUEST
    value: 250m
  - name: MEMORY_REQUEST
    value: 512Mi
  - name: IMAGE
    value: quay.io/tangerine/tangerine-backend
  - name: IMAGE_TAG
    value: latest

objects:
# tangerine backend
- kind: Secret
  apiVersion: v1
  metadata:
    name: llm-api-key
  stringData:
    api_key: yourApiKey
  type: Opaque

- kind: Secret
  apiVersion: v1
  metadata:
    name: embed-api-key
  stringData:
    api_key: yourApiKey
  type: Opaque

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: tangerine-backend
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 33%
    minReadySeconds: 5
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: tangerine-backend
    template:
      metadata:
        labels:
          app.kubernetes.io/name: tangerine-backend
      spec:
        containers:
          - resources:
              requests:
                memory: ${MEMORY_REQUEST}
                cpu: ${CPU_REQUEST}
              limits:
                memory: ${MEMORY_LIMIT}
                cpu: ${CPU_LIMIT}
            readinessProbe:
              httpGet:
                path: /ping
                port: 8000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            livenessProbe:
              httpGet:
                path: /ping
                port: 8000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: tangerine-backend
            env:
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.user
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.password
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.name
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.host
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.port
              - name: LLM_BASE_URL
                value: ${LLM_BASE_URL}
              - name: EMBED_BASE_URL
                value: ${EMBED_BASE_URL}
              - name: LLM_MODEL_NAME
                value: ${LLM_MODEL_NAME}
              - name: LLM_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: llm-api-key
                    key: api_key
              - name: EMBED_MODEL_NAME
                value: ${EMBED_MODEL_NAME}
              - name: EMBED_QUERY_PREFIX
                value: ${EMBED_QUERY_PREFIX}
              - name: EMBED_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: embed-api-key
                    key: api_key
            securityContext:
              capabilities: {}
              privileged: false
            ports:
              - name: tangerine-backend
                containerPort: 8000
                protocol: TCP
            imagePullPolicy: IfNotPresent
            terminationMessagePolicy: File
            image: ${IMAGE}:${IMAGE_TAG}
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

- kind: Service
  apiVersion: v1
  metadata:
    name: tangerine-backend
    labels:
      app.kubernetes.io/name: tangerine-backend
  spec:
    selector:
      app.kubernetes.io/name: tangerine-backend
    ports:
      - name: tangerine-backend
        protocol: TCP
        port: 8000
        targetPort: 8000
