---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tangerine-ingress
objects:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: tangerine
  spec:
    rules:
    - host: ${HOSTNAME}
      http:
        paths:
        - backend:
            service:
              name: tangerine-backend
              port:
                number: 5000
          path: /api
          pathType: Prefix
        - backend:
            service:
              name: tangerine-frontend
              port:
                number: 3000
          path: /
          pathType: Prefix
    tls:
    - {}

parameters:
- name: HOSTNAME
  required: true
