---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: pgvector

objects:
# postgres vector DB
- kind: Secret
  apiVersion: v1
  metadata:
    name: vector-db
  stringData:
    db.name: vectordb
    db.password: ${POSTGRES_PASSWORD}
    db.user: ${POSTGRES_USER}
    db.host: postgresql
    db.port: "5432"
  type: Opaque

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: postgresql
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${POSTGRES_VOLUME_SIZE}
    volumeMode: Filesystem

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: postgresql
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: postgresql
    template:
      metadata:
        labels:
          app.kubernetes.io/name: postgresql
      spec:
        volumes:
          - name: postgresql-data
            persistentVolumeClaim:
              claimName: postgresql
        containers:
          - resources:
              requests:
                memory: 512Mi
                cpu: 250m
              limits:
                memory: 512Mi
                cpu: 1
            readinessProbe:
              exec:
                command:
                  - /usr/libexec/check-container
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: postgresql
            livenessProbe:
              exec:
                command:
                  - /usr/libexec/check-container
                  - '--live'
              initialDelaySeconds: 120
              timeoutSeconds: 10
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            env:
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.user
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.password
              - name: POSTGRESQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: vector-db
                    key: db.name
            securityContext:
              capabilities: {}
              privileged: false
            ports:
              - containerPort: 5432
                protocol: TCP
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: postgresql-data
                mountPath: /var/lib/pgsql/data
            terminationMessagePolicy: File
            image: 'quay.io/tangerine/postgresql-16-pgvector-0-7-3-c9s:0.0.1'
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

- kind: Service
  apiVersion: v1
  metadata:
    name: postgresql
  spec:
    selector:
      app.kubernetes.io/name: postgresql
    ports:
      - name: postgresql
        protocol: TCP
        port: 5432
        targetPort: 5432

parameters:
  - name: POSTGRES_USER
    required: true
  - name: POSTGRES_PASSWORD
    required: true
  - name: POSTGRES_VOLUME_SIZE
    value: "20Gi"
