name: gh-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        show-progress: false

    - name: Setup python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.2.0
      with:
        python-version-file: 'Pipfile' # Read python version from a file Pipfile
        cache: 'pipenv'

    - name: Run pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        show-progress: false

    - name: Setup python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.2.0
      with:
        python-version-file: 'Pipfile' # Read python version from a file Pipfile
        cache: 'pipenv'

    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

    - name: Install dependencies and dev packages
      run: pipenv sync --dev

    - name: Run pytest
      run: pipenv run pytest -v -s
