name: pre-commit

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache pipenv
      uses: actions/cache@v3
      id: cache-pipenv
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv

    - name: Install pipenv
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install Dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --system --deploy --dev

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
