kind: Secret
apiVersion: v1
metadata:
  name: s3-credentials
stringData:
  aws_access_key_id: your_key_id
  aws_secret_access_key: your_access_key
  aws_region: your_aws_region
  endpoint: your_s3_endpoint
type: Opaque