---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tangerine-backend-s3sync

objects:
- kind: CronJob
  apiVersion: batch/v1
  metadata:
    name: tangerine-s3-sync
  spec:
    suspend: ${{S3_SYNC_SUSPEND}}
    schedule: "*/30 * * * *"
    concurrencyPolicy: "Forbid"
    jobTemplate:
      spec:
        template:
          spec:
            volumes:
              - name: s3sync-config
                configMap:
                  name: s3sync-config
            containers:
              - name: tangerine-s3sync
                command: ["flask", "s3sync"]
                volumeMounts:
                  - name: s3sync-config
                    mountPath: /s3sync-config
                resources:
                  requests:
                    memory: 256Mi
                    cpu: 250m
                  limits:
                    memory: 512Mi
                    cpu: 500m
                env:
                  - name: S3_SYNC_CONFIG_FILE
                    value: /s3sync-config/s3.yaml
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: ${AWS_S3_SECRET_NAME}
                        key: aws_access_key_id
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: ${AWS_S3_SECRET_NAME}
                        key: aws_secret_access_key
                  - name: AWS_DEFAULT_REGION
                    valueFrom:
                      secretKeyRef:
                        name: ${AWS_S3_SECRET_NAME}
                        key: aws_region
                  - name: AWS_ENDPOINT_URL_S3
                    valueFrom:
                      secretKeyRef:
                        name: ${AWS_S3_SECRET_NAME}
                        key: endpoint
                  - name: DB_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: vector-db
                        key: db.user
                  - name: DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: vector-db
                        key: db.password
                  - name: DB_NAME
                    valueFrom:
                      secretKeyRef:
                        name: vector-db
                        key: db.name
                  - name: DB_HOST
                    valueFrom:
                      secretKeyRef:
                        name: vector-db
                        key: db.host
                  - name: DB_PORT
                    valueFrom:
                      secretKeyRef:
                        name: vector-db
                        key: db.port
                  - name: EMBED_BASE_URL
                    value: ${EMBED_BASE_URL}
                  - name: EMBED_MODEL_NAME
                    value: ${EMBED_MODEL_NAME}
                  - name: EMBED_QUERY_PREFIX
                    value: ${EMBED_QUERY_PREFIX}
                imagePullPolicy: Always  # TODO: change to "IfNotPresent" when project stabilizes
                image: 'quay.io/tangerine/tangerine-backend:latest'
            restartPolicy: Never

parameters:
  - name: AWS_S3_SECRET_NAME
    value: s3-credentials
  - name: S3_SYNC_SUSPEND
    value: "false"
  - name: EMBED_BASE_URL
    value: http://text-embeddings-inference:3000/v1
  - name: EMBED_MODEL_NAME
    value: Snowflake/snowflake-arctic-embed-m-long
  - name: EMBED_QUERY_PREFIX
    value: "Represent this sentence for searching relevant passages"
